config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'home/about'
  get 'home/popular'
  get 'home/top_rated'
  get 'home/now_showing'
  get 'home/upcoming'
  get 'home/details'
  get 'home/tv_details'
  get 'home/tv_popular'
  get 'home/tv_top_rated'
  get 'home/tv_showing'
  get 'home/tv_today'
  get 'home/search'
  post '/home/search' => 'home/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def popular
    require 'net/http'
    require 'json'
    @url = 'https://api.themoviedb.org/3/movie/popular?api_key=d87c00b6a00ae74e930c063e106d6b4d&language=en-US&page=1'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @popular = JSON.parse(@response)
  end

  def now_showing
    require 'net/http'
    require 'json'
    @url = 'https://api.themoviedb.org/3/movie/now_playing?api_key=d87c00b6a00ae74e930c063e106d6b4d&language=en-US&page=1'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @now_showing = JSON.parse(@response)
  end

  def top_rated
    require 'net/http'
    require 'json'
    @url = 'https://api.themoviedb.org/3/movie/top_rated?api_key=d87c00b6a00ae74e930c063e106d6b4d&language=en-US&page=1'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @top_rated = JSON.parse(@response)
  end

  def upcoming
    require 'net/http'
    require 'json'
    @url = 'https://api.themoviedb.org/3/movie/upcoming?api_key=d87c00b6a00ae74e930c063e106d6b4d&language=en-US&page=1'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @upcoming = JSON.parse(@response)
  end
  
  def tv_popular
    require 'net/http'
    require 'json'
    @url = 'https://api.themoviedb.org/3/tv/popular?api_key=d87c00b6a00ae74e930c063e106d6b4d&language=en-US&page=1'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @tv_popular = JSON.parse(@response)
  end
  
  def tv_top_rated
    require 'net/http'
    require 'json'
    @url = 'https://api.themoviedb.org/3/tv/top_rated?api_key=d87c00b6a00ae74e930c063e106d6b4d&language=en-US&page=1'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @tv_top_rated = JSON.parse(@response)  
  end
  
  def tv_showing
    require 'net/http'
    require 'json'
    @url = 'https://api.themoviedb.org/3/tv/on_the_air?api_key=d87c00b6a00ae74e930c063e106d6b4d&language=en-US&page=1'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @tv_showing = JSON.parse(@response)  
  end
  
  def tv_today
    require 'net/http'
    require 'json'
    @url = 'https://api.themoviedb.org/3/tv/airing_today?api_key=d87c00b6a00ae74e930c063e106d6b4d&language=en-US&page=1'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @tv_today = JSON.parse(@response)  
  end
  
  def search
  end
    
  def about
  end
  
  def details
  end
  
  def tv_details
  end
end

class Details    
  
    attr_accessor :id

    def initialize(id)
        @movie_id = id
    end

    def movie
        @base_url = "https://api.themoviedb.org/3/movie/"
        @api_key = "?api_key=d87c00b6a00ae74e930c063e106d6b4d"
        @lang = "&language=en-US"
        @url = @base_url + @movie_id + @api_key + @lang
        require 'net/http'
        require 'json'
        @uri = URI(@url)
        @response = Net::HTTP.get(@uri)
        @details = JSON.parse(@response)
        return @details
    end
end

class Details_TV    
  
    attr_accessor :id

    def initialize(id)
        @tv_id = id
    end

    def series
        @base_url = "https://api.themoviedb.org/3/tv/"
        @api_key = "?api_key=d87c00b6a00ae74e930c063e106d6b4d"
        @lang = "&language=en-US"
        @url = @base_url + @tv_id + @api_key + @lang
        require 'net/http'
        require 'json'
        @uri = URI(@url)
        @response = Net::HTTP.get(@uri)
        @tv_details = JSON.parse(@response)
        return @tv_details
    end
end

class Search_movies
    
    attr_accessor :query

    def initialize(query)
        @query = query
    end
        
    def search_movies
        @base_url = "https://api.themoviedb.org/3/search/movie?api_key=d87c00b6a00ae74e930c063e106d6b4d&language=en-US"
        @movie_query = "&query=" + query
        @page = "&page=1"
        @adult = "&include_adult=false"
        @url = @base_url + @movie_query + @page + @adult
        require 'net/http'
        require 'json'
        @uri = URI(@url)
        @response = Net::HTTP.get(@uri)
        @movie_search = JSON.parse(@response)
        return @movie_search
    end
end

    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissible">
        <button class="close" data-dismiss="alert">
            <i class="glyphicon glyphicon-remove-circle"></i>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "CineInfo", root_path, class: "navbar-brand" %></li>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Movies <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Popular", home_popular_path %></li>
            <li><%= link_to "Upcoming", home_upcoming_path %></li>
            <li><%= link_to "Now Showing", home_now_showing_path %></li>
            <li><%= link_to "Top Rated", home_top_rated_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Series <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Popular TV", home_tv_popular_path %></li>
            <li><%= link_to "Top Rated", home_tv_top_rated_path %></li>
            <li><%= link_to "On the Air", home_tv_showing_path %></li>
            <li><%= link_to "Airing Today", home_tv_today_path %></li>
          </ul>
        </li>
        <li><%= link_to "Search", home_search_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", home_about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Register", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>About</h1>
<p>This is the about page.</p>

app/views/home/details.html.erb
<h1>Movie Details</h1>

<br/><br/>

<% @movie_id = params["format"] %>

<%= Details.new(@movie_id).movie %>

<br/><br/>

<%= Details.new(@movie_id).movie["title"] %><br/>
<%= Details.new(@movie_id).movie["vote_average"] %><br/>
<%= Details.new(@movie_id).movie["release_date"] %><br/>
<%= Details.new(@movie_id).movie["overview"] %><br/>

app/views/home/index.html.erb
<h1>Welcome</h1>
<p>This is the home page.</p>

app/views/home/now_showing.html.erb
<h1>Now Showing</h1>

<br/><br/>

<% for x in @now_showing["results"] %>

    <% @id = x["id"] %>
    <%= link_to x["title"], home_details_path(@id) %><br/>
    <%= x["release_date"] %><br/>
    <%= x["vote_average"] %><br/><br/>

<% end %>

app/views/home/popular.html.erb
<h1>Popular Movies</h1>

<br/><br/>

<% for x in @popular["results"] %>
    
    <div class="panel" >
        <% @id = x["id"] %>
        <%= link_to x["title"], home_details_path(@id) %><br/>
        <%= x["release_date"] %><br/>
        <%= x["vote_average"] %>
    </div>

<% end %>

app/views/home/search.html.erb
 <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Search Movies</h3>
  </div>
  <form class="form-inline">
    <div class="panel-body">
        <div class="form-group">
            <%= form_tag home_search_path, :method => 'POST' do %>
                <%= text_field_tag 'sym', nil, placeholder: 'Enter Movie Name', size: 50, class: "form-control" %>
                <%= submit_tag 'Search', class:"btn btn-info" %>
            <% end %>
            <br/><br>
            
            
            
            
            
            
            
        </div>
    </div>
  </form>  
</div>
 
<!--<% if @movie_search %>
    <% for x in @movie_search["results"] %>
        <%= x["title"] %><br/>
        <%= x["release_date"] %><br/>
        <%= x["vote_average"] %><br/>
        <%= x["overview"] %><br/><br/>
    <% end %>
<% end %>-->

app/views/home/top_rated.html.erb
<h1>Top Rated</h1>

<br/><br/>

<% for x in @top_rated["results"] %>

    <% @id = x["id"] %>
    <%= link_to x["title"], home_details_path(@id) %><br/>
    <%= x["release_date"] %><br/>
    <%= x["vote_average"] %><br/><br/>

<% end %>

app/views/home/tv_details.html.erb
<h1>Series Details</h1>

<br/><br/>

<% @tv_id = params["format"] %>

<% Details_TV.new(@tv_id).series %>

<br/><br/>

<%= Details_TV.new(@tv_id).series["name"] %><br/>
<%= Details_TV.new(@tv_id).series["vote_average"] %><br/>
<%= Details_TV.new(@tv_id).series["first_air_date"] %><br/><br/>
<%= Details_TV.new(@tv_id).series["overview"] %><br/>


<% Details_TV.new(@tv_id).series["last_episode_to_air"]["name"] %><br/>

app/views/home/tv_showing.html.erb
<h1>On the Air</h1> 


<% @tv_showing %>

<% for x in @tv_showing["results"] %>
    
    <div class="panel" >
        <% @id = x["id"] %>
        <%= link_to x["name"], home_tv_details_path(@id) %><br/>
        <%= x["first_air_date"] %><br/>
        <%= x["vote_average"] %>
    </div>

<% end %>

app/views/home/tv_today.html.erb
<h1>Airting Today</h1>


<% @tv_today %>


<% for x in @tv_today["results"] %>
    
    <div class="panel" >
        <% @id = x["id"] %>
        <%= link_to x["name"], home_tv_details_path(@id) %><br/>
        <%= x["first_air_date"] %><br/>
        <%= x["vote_average"] %>
    </div>

<% end %>

app/views/home/tv_top_rated.html.erb
<h1>Top Rated TV</h1> 


<% @tv_top_rated %>

<% for x in @tv_top_rated["results"] %>
    
    <div class="panel" >
        <% @id = x["id"] %>
        <%= link_to x["name"], home_tv_details_path(@id) %><br/>
        <%= x["first_air_date"] %><br/>
        <%= x["vote_average"] %>
    </div>

<% end %>

app/views/home/upcoming.html.erb
<h1>Upcoming Movies</h1>

<br/><br/>

<% for x in @upcoming["results"] %>

    <% @id = x["id"] %>
    <%= link_to x["title"], home_details_path(@id) %><br/>
    <%= x["release_date"] %><br/>
    <%= x["vote_average"] %><br/><br/>
    
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CineInfo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'home/navbar' %>


    <div class="container">
        <%= render 'home/flash' %>
        <%= yield %>
    </div>

  </body>
</html>